# Generated by Django 4.1.4 on 2022-12-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('item_code', models.CharField(max_length=50, verbose_name='Артикул')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('status', models.CharField(choices=[('AVAILABLE', 'В наличии'), ('ORDER', 'Под заказ'), ('AWAIT', 'Ожидается поступление'), ('UNAVAILABLE', 'Нет в наличии'), ('WITHDRAWN', 'Не производится')], max_length=15, verbose_name='Статус')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
            ],
        ),
    ]
